# -*- coding: utf-8 -*-
"""Complex_modulus.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WRPqQzefqpsfI6JBFgeWaFWmyqZfEyRr
"""



for i in range(1,100):
  modulus = abs((3+4j)**i)
  if modulus >= 100:
    print('The min power n is:', i)
    break