# -*- coding: utf-8 -*-
"""Fibonacciipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TNaOSLFKWG9K5QUuqxUsnj1LZvYR9lTU
"""

a, b = 0, 1

while a < 100:
    print(a, end=", ")
    print()
    a, b = b, a+b